class Event:
    """Events the client is expected to consume and react to."""
    def to_dict(self):
        return self.__dict__


class AssistantSpeechUpdateEvent(Event):
    """Event indicating a change in the assistant speaking state."""
    def __init__(self, speaking: bool):
        self.event_type = "assistant-speaking"
        self.speaking = speaking


class UserTranscriptEvent(Event):
    """Event carrying a user speech transcript."""
    def __init__(self, text: str, is_final: bool):
        self.event_type = "user-transcript"
        self.text = text
        self.is_final = is_final


class ModelOutputEvent(Event):
    """Event containing textual output tokens generated by the LLM."""
    def __init__(self, output: str):
        self.event_type = "model-output"
        self.output = output


class ToolCallEvent(Event):
    """Event representing a tool execution requested by the LLM."""
    def __init__(self, name: str, arguments: dict, execution_id: str):
        self.event_type = "tool-call"
        self.name = name
        self.arguments = arguments
        self.execution_id = execution_id


class ToolCallResultEvent(Event):
    """Event carrying the result of a completed tool execution."""
    def __init__(self, name: str, result: str, execution_id: str):
        self.event_type = "tool-call-result"
        self.name = name
        self.result = result
        self.execution_id = execution_id


class StartCallEvent(Event):
    """Event indicating the success or failure of a call start attempt with VAPI."""
    def __init__(self, started: bool):
        self.event_type = "start-call"
        self.started = started


class EndCallEvent(Event):
    """Event indicating that a call has ended, either expectedly or unexpectedly."""
    def __init__(self, expected: bool, reason: str = None):
        self.event_type = "end-call"
        self.expected = expected
        self.reason = reason # Used in case of expected termination

class UserActivityDetectedEvent(Event):
    """Event indicating that user activity has been detected."""
    def __init__(self):
        self.event_type = "user-activity-detected"